### ISSUE TITLE
分布式事务第一个文档-InnoDB实现原理-管理器进行管理，的图片是不是有问题

### ISSUE THREAD

**Issue by zhaoyuguang** [javagrowing/JGrowing#25]
https://github.com/javagrowing/JGrowing/blob/master/%E5%88%86%E5%B8%83%E5%BC%8F/%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1/%E5%86%8D%E6%9C%89%E4%BA%BA%E9%97%AE%E4%BD%A0%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1%EF%BC%8C%E8%BF%99%E7%AF%87%E6%96%87%E7%AB%A0%E6%89%94%E7%BB%99%E4%BB%96.md

**Comment by CoffeeLatte007** [comment]
没有问题

**Comment by zhaoyuguang** [comment]
Sorry is my network issue
